/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import java.awt.Color;

/**
 *
 * @author jeison tamara
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        grupoBoton.add(radioBoton1);
        grupoBoton.add(radioBoton2);
        grupoBoton.add(radioBoton3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBoton = new javax.swing.ButtonGroup();
        menuDesplegable = new javax.swing.JPopupMenu();
        ventanaMax = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        ventanaMin = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        colorVentana = new javax.swing.JMenu();
        cambioColorRojo = new javax.swing.JMenuItem();
        cambioColorAzul = new javax.swing.JMenuItem();
        panel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menú = new javax.swing.JMenu();
        menuItemInicio = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        casilla1 = new javax.swing.JCheckBoxMenuItem();
        casilla2 = new javax.swing.JCheckBoxMenuItem();
        casilla3 = new javax.swing.JCheckBoxMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        radioBoton1 = new javax.swing.JRadioButtonMenuItem();
        radioBoton2 = new javax.swing.JRadioButtonMenuItem();
        radioBoton3 = new javax.swing.JRadioButtonMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuItemSalir = new javax.swing.JMenuItem();

        ventanaMax.setText("Ventana mas grande");
        ventanaMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventanaMaxActionPerformed(evt);
            }
        });
        menuDesplegable.add(ventanaMax);
        menuDesplegable.add(jSeparator4);

        ventanaMin.setText("Ventana mas pequeña");
        ventanaMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventanaMinActionPerformed(evt);
            }
        });
        menuDesplegable.add(ventanaMin);
        menuDesplegable.add(jSeparator5);

        colorVentana.setText("Cambiar color");

        cambioColorRojo.setText("Ventana roja");
        cambioColorRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambioColorRojoActionPerformed(evt);
            }
        });
        colorVentana.add(cambioColorRojo);

        cambioColorAzul.setText("Color azul");
        cambioColorAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambioColorAzulActionPerformed(evt);
            }
        });
        colorVentana.add(cambioColorAzul);

        menuDesplegable.add(colorVentana);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        menú.setText("Menú");
        menú.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N

        menuItemInicio.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        menuItemInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoinicio.png"))); // NOI18N
        menuItemInicio.setText("Inicio");
        menuItemInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInicioActionPerformed(evt);
            }
        });
        menú.add(menuItemInicio);
        menú.add(jSeparator1);

        jMenu1.setText("SubMenú1");

        casilla1.setSelected(true);
        casilla1.setText("item1");
        jMenu1.add(casilla1);

        casilla2.setSelected(true);
        casilla2.setText("item2");
        jMenu1.add(casilla2);

        casilla3.setSelected(true);
        casilla3.setText("item3");
        jMenu1.add(casilla3);

        menú.add(jMenu1);
        menú.add(jSeparator3);

        jMenu2.setText("SubMenú2");

        radioBoton1.setSelected(true);
        radioBoton1.setText("radioBoton1");
        jMenu2.add(radioBoton1);

        radioBoton2.setSelected(true);
        radioBoton2.setText("radioBoton2");
        radioBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBoton2ActionPerformed(evt);
            }
        });
        jMenu2.add(radioBoton2);

        radioBoton3.setSelected(true);
        radioBoton3.setText("radioBoton3");
        jMenu2.add(radioBoton3);

        menú.add(jMenu2);
        menú.add(jSeparator2);

        menuItemSalir.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        menuItemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconosalir.png"))); // NOI18N
        menuItemSalir.setText("Salir");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menú.add(menuItemSalir);

        jMenuBar1.add(menú);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemInicioActionPerformed

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void radioBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBoton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBoton2ActionPerformed

    private void panelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseReleased
        if(evt.isPopupTrigger()){
            menuDesplegable.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_panelMouseReleased

    private void ventanaMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventanaMaxActionPerformed
        this.setSize(500, 500);
    }//GEN-LAST:event_ventanaMaxActionPerformed

    private void ventanaMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventanaMinActionPerformed
        this.setSize(300,300);
    }//GEN-LAST:event_ventanaMinActionPerformed

    private void cambioColorRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambioColorRojoActionPerformed
        panel.setBackground(Color.red);
    }//GEN-LAST:event_cambioColorRojoActionPerformed

    private void cambioColorAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambioColorAzulActionPerformed
        panel.setBackground(Color.blue);
    }//GEN-LAST:event_cambioColorAzulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cambioColorAzul;
    private javax.swing.JMenuItem cambioColorRojo;
    private javax.swing.JCheckBoxMenuItem casilla1;
    private javax.swing.JCheckBoxMenuItem casilla2;
    private javax.swing.JCheckBoxMenuItem casilla3;
    private javax.swing.JMenu colorVentana;
    private javax.swing.ButtonGroup grupoBoton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu menuDesplegable;
    private javax.swing.JMenuItem menuItemInicio;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenu menú;
    private javax.swing.JPanel panel;
    private javax.swing.JRadioButtonMenuItem radioBoton1;
    private javax.swing.JRadioButtonMenuItem radioBoton2;
    private javax.swing.JRadioButtonMenuItem radioBoton3;
    private javax.swing.JMenuItem ventanaMax;
    private javax.swing.JMenuItem ventanaMin;
    // End of variables declaration//GEN-END:variables
}
